# Generated by Django 5.1.2 on 2024-10-25 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_subject_alter_schedule_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
    ]
