# Generated by Django 5.1.2 on 2024-10-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_schedule_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(help_text='Среда не рабочий день', verbose_name='Время начала занятий'),
        ),
    ]
