# Generated by Django 5.1.2 on 2024-10-29 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_schedule_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'ФРасписание', 'verbose_name_plural': 'АРасписания'},
        ),
    ]
