# Generated by Django 5.1.2 on 2024-10-29 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_schedule_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='name',
        ),
    ]
