# Generated by Django 5.1.2 on 2024-10-29 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_remove_schedule_teacher_remove_schedule_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'ФРасписание', 'verbose_name_plural': 'АРасписания'},
        ),
    ]
