# Generated by Django 5.1.2 on 2024-10-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_schedule_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
    ]
