# Generated by Django 5.1.2 on 2024-10-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_schedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(default=1, verbose_name='Время окончания занятий'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала занятий'),
        ),
    ]
